// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWi3gGD_KskLbnkN9WJe1BDtkVLXkHH0A',
    appId: '1:754997243346:web:f1209f631ef74772beac0b',
    messagingSenderId: '754997243346',
    projectId: 'appvet-6a0aa',
    authDomain: 'appvet-6a0aa.firebaseapp.com',
    storageBucket: 'appvet-6a0aa.appspot.com',
    measurementId: 'G-32N39K217V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxJ2qTJenKlQU2CwuE053ypOji2jTKlBw',
    appId: '1:754997243346:android:e8e3389f56542c9cbeac0b',
    messagingSenderId: '754997243346',
    projectId: 'appvet-6a0aa',
    storageBucket: 'appvet-6a0aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhI58ttogGVyQwSLnHG5m3WR4bSs8LY6s',
    appId: '1:754997243346:ios:1cdae5565d0fefe1beac0b',
    messagingSenderId: '754997243346',
    projectId: 'appvet-6a0aa',
    storageBucket: 'appvet-6a0aa.appspot.com',
    iosBundleId: 'com.example.appvet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhI58ttogGVyQwSLnHG5m3WR4bSs8LY6s',
    appId: '1:754997243346:ios:1cdae5565d0fefe1beac0b',
    messagingSenderId: '754997243346',
    projectId: 'appvet-6a0aa',
    storageBucket: 'appvet-6a0aa.appspot.com',
    iosBundleId: 'com.example.appvet',
  );

}